language: php

php:
  - 5.4
  - 5.3

env:
  - DB=sqlite

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev

script: php tests/lint.php tests/ lib/ && phpunit --verbose
