language: php

php:
  - 5.5
  - 5.4

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev

script: VERBOSE=true php tests/lint.php tests/ lib/ && ./tests/run-tests.sh -s tests/
