language: php

php:
  - 5.4
  - 5.3

env:
  - DB=sqlite

before_script:
  - "sh -c 'curl -s http://getcomposer.org/installer | php'"
  - "sh -c 'php composer.phar install --quiet'"

script: php tests/lint.php tests/ lib/ && phpunit --verbose
