<?php // vim: ts=4 sw=4 ai:
/**
 * This file is part of Lohini
 *
 * @copyright (c) 2010, 2011 Lopo <lopo@lohini.net>
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License Version 3
 */
namespace Lohini\Loaders;

/**
 * Lohini auto loader is responsible for loading Lohini classes and interfaces.
 *
 * @author Lopo <lopo@lohini.net>
 */
class LohiniLoader
extends \Nette\Loaders\AutoLoader
{
	/** @var LohiniLoader */
	private static $instance;
	/** @var array */
	public $list=array(
		'lohini\application\application' => '/Application/Application.php',
		'lohini\application\invalidpresenterexception' => '/Application/InvalidPresenterException.php',
		'lohini\application\presenterfactory' => '/Application/PresenterFactory.php',
		'lohini\application\ui\control' => '/Application/UI/Control.php',
		'lohini\application\ui\form' => '/Application/UI/Form.php',
		'lohini\application\ui\presenter' => '/Application/UI/Presenter.php',
		'lohini\components\datagrid\action' => '/Components/DataGrid/Action.php',
		'lohini\components\datagrid\columns\actioncolumn' => '/Components/DataGrid/Columns/ActionColumn.php',
		'lohini\components\datagrid\columns\boolcolumn' => '/Components/DataGrid/Columns/BoolColumn.php',
		'lohini\components\datagrid\columns\checkboxcolumn' => '/Components/DataGrid/Columns/CheckboxColumn.php',
		'lohini\components\datagrid\columns\column' => '/Components/DataGrid/Columns/Column.php',
		'lohini\components\datagrid\columns\datecolumn' => '/Components/DataGrid/Columns/DateColumn.php',
		'lohini\components\datagrid\columns\icolumn' => '/Components/DataGrid/Columns/IColumn.php',
		'lohini\components\datagrid\columns\imagecolumn' => '/Components/DataGrid/Columns/ImageColumn.php',
		'lohini\components\datagrid\columns\numericcolumn' => '/Components/DataGrid/Columns/NumericColumn.php',
		'lohini\components\datagrid\columns\positioncolumn' => '/Components/DataGrid/Columns/PositionColumn.php',
		'lohini\components\datagrid\columns\textcolumn' => '/Components/DataGrid/Columns/TextColumn.php',
		'lohini\components\datagrid\datagrid' => '/Components/DataGrid/DataGrid.php',
		'lohini\components\datagrid\filters\checkboxfilter' => '/Components/DataGrid/Filters/CheckboxFilter.php',
		'lohini\components\datagrid\filters\columnfilter' => '/Components/DataGrid/Filters/ColumnFilter.php',
		'lohini\components\datagrid\filters\datefilter' => '/Components/DataGrid/Filters/DateFilter.php',
		'lohini\components\datagrid\filters\icolumnfilter' => '/Components/DataGrid/Filters/IColumnFilter.php',
		'lohini\components\datagrid\filters\selectboxfilter' => '/Components/DataGrid/Filters/SelectboxFilter.php',
		'lohini\components\datagrid\filters\textfilter' => '/Components/DataGrid/Filters/TextFilter.php',
		'lohini\components\datagrid\iaction' => '/Components/DataGrid/IAction.php',
		'lohini\components\datagrid\renderers\conventional' => '/Components/DataGrid/Renderers/Conventional.php',
		'lohini\components\datagrid\renderers\irenderer' => '/Components/DataGrid/Renderers/IRenderer.php',
		'lohini\components\gravatar' => '/Components/Gravatar.php',
		'lohini\components\treeview\renderers\conventional' => '/Components/TreeView/Renderers/Conventional.php',
		'lohini\components\treeview\renderers\irenderer' => '/Components/TreeView/Renderers/IRenderer.php',
		'lohini\components\treeview\treeview' => '/Components/TreeView/TreeView.php',
		'lohini\components\treeview\treeviewlink' => '/Components/TreeView/TreeViewLink.php',
		'lohini\components\treeview\treeviewnode' => '/Components/TreeView/TreeViewNode.php',
		'lohini\core' => '/Core.php',
		'lohini\database\connection' => '/Database/Connection.php',
		'lohini\database\datasources\datasource' => '/Database/DataSources/DataSource.php',
		'lohini\database\datasources\dibi\datasource' => '/Database/DataSources/Dibi/DataSource.php',
		'lohini\database\datasources\dibi\fluent' => '/Database/DataSources/Dibi/Fluent.php',
		'lohini\database\datasources\doctrine\querybuilder' => '/Database/DataSources/Doctrine/QueryBuilder.php',
		'lohini\database\datasources\doctrine\utils\countingastwalker' => '/Database/DataSources/Doctrine/Utils/CountingASTWalker.php',
		'lohini\database\datasources\doctrine\utils\distinctastwalker' => '/Database/DataSources/Doctrine/Utils/DistinctASTWalker.php',
		'lohini\database\datasources\idatasource' => '/Database/DataSources/IDataSource.php',
		'lohini\database\datasources\mapped' => '/Database/DataSources/Mapped.php',
		'lohini\database\datasources\nettedb\db' => '/Database/DataSources/NetteDB/DB.php',
		'lohini\database\datasources\phparray\phparray' => '/Database/DataSources/PHPArray/PHPArray.php',
		'lohini\database\datasources\utils\wildcardhelper' => '/Database/DataSources/Utils/WildcardHelper.php',
		'lohini\database\doctrine\annotations\cachedreader' => '/Database/Doctrine/Annotations/CachedReader.php',
		'lohini\database\doctrine\basecontainer' => '/Database/Doctrine/BaseContainer.php',
		'lohini\database\doctrine\cache' => '/Database/Doctrine/Cache.php',
		'lohini\database\doctrine\duplicateentryexception' => '/Database/Doctrine/DuplicateEntryException.php',
		'lohini\database\doctrine\emptyvalueexception' => '/Database/Doctrine/EmptyValueException.php',
		'lohini\database\doctrine\exception' => '/Database/Doctrine/Exception.php',
		'lohini\database\doctrine\invalidentityexception' => '/Database/Doctrine/InvalidEntityException.php',
		'lohini\database\doctrine\managerexception' => '/Database/Doctrine/ManagerException.php',
		'lohini\database\doctrine\mapping\entitycomponentmapper' => '/Database/Doctrine/Mapping/EntityComponentMapper.php',
		'lohini\database\doctrine\mapping\fieldtypes\arraytype' => '/Database/Doctrine/Mapping/FieldTypes/ArrayType.php',
		'lohini\database\doctrine\mapping\fieldtypes\biginttype' => '/Database/Doctrine/Mapping/FieldTypes/BigIntType.php',
		'lohini\database\doctrine\mapping\fieldtypes\booleantype' => '/Database/Doctrine/Mapping/FieldTypes/BooleanType.php',
		'lohini\database\doctrine\mapping\fieldtypes\callbacktype' => '/Database/Doctrine/Mapping/FieldTypes/CallbackType.php',
		'lohini\database\doctrine\mapping\fieldtypes\datetimetype' => '/Database/Doctrine/Mapping/FieldTypes/DateTimeType.php',
		'lohini\database\doctrine\mapping\fieldtypes\datetimetztype' => '/Database/Doctrine/Mapping/FieldTypes/DateTimeTzType.php',
		'lohini\database\doctrine\mapping\fieldtypes\datetype' => '/Database/Doctrine/Mapping/FieldTypes/DateType.php',
		'lohini\database\doctrine\mapping\fieldtypes\decimaltype' => '/Database/Doctrine/Mapping/FieldTypes/DecimalType.php',
		'lohini\database\doctrine\mapping\fieldtypes\floattype' => '/Database/Doctrine/Mapping/FieldTypes/FloatType.php',
		'lohini\database\doctrine\mapping\fieldtypes\integertype' => '/Database/Doctrine/Mapping/FieldTypes/IntegerType.php',
		'lohini\database\doctrine\mapping\fieldtypes\objecttype' => '/Database/Doctrine/Mapping/FieldTypes/ObjectType.php',
		'lohini\database\doctrine\mapping\fieldtypes\passwordtype' => '/Database/Doctrine/Mapping/FieldTypes/PasswordType.php',
		'lohini\database\doctrine\mapping\fieldtypes\smallinttype' => '/Database/Doctrine/Mapping/FieldTypes/SmallIntType.php',
		'lohini\database\doctrine\mapping\fieldtypes\stringtype' => '/Database/Doctrine/Mapping/FieldTypes/StringType.php',
		'lohini\database\doctrine\mapping\fieldtypes\texttype' => '/Database/Doctrine/Mapping/FieldTypes/TextType.php',
		'lohini\database\doctrine\mapping\fieldtypes\timetype' => '/Database/Doctrine/Mapping/FieldTypes/TimeType.php',
		'lohini\database\doctrine\mapping\fieldtypes\vardatetimetype' => '/Database/Doctrine/Mapping/FieldTypes/VarDateTimeType.php',
		'lohini\database\doctrine\mapping\ifieldtype' => '/Database/Doctrine/Mapping/IFieldType.php',
		'lohini\database\doctrine\mapping\typemapper' => '/Database/Doctrine/Mapping/TypeMapper.php',
		'lohini\database\doctrine\odm\container' => '/Database/Doctrine/ODM/Container.php',
		'lohini\database\doctrine\odm\couchdbhelper' => '/Database/Doctrine/ODM/CouchDBHelper.php',
		'lohini\database\doctrine\odm\mapping\driver\annotationdriver' => '/Database/Doctrine/ODM/Mapping/Driver/AnnotationDriver.php',
		'lohini\database\doctrine\orm\baseservice' => '/Database/Doctrine/ORM/BaseService.php',
		'lohini\database\doctrine\orm\container' => '/Database/Doctrine/ORM/Container.php',
		'lohini\database\doctrine\orm\diagnostics\panel' => '/Database/Doctrine/ORM/Diagnostics/Panel.php',
		'lohini\database\doctrine\orm\entities\baseentity' => '/Database/Doctrine/ORM/Entities/BaseEntity.php',
		'lohini\database\doctrine\orm\entities\identifiedentity' => '/Database/Doctrine/ORM/Entities/IdentifiedEntity.php',
		'lohini\database\doctrine\orm\entities\namedentity' => '/Database/Doctrine/ORM/Entities/NamedEntity.php',
		'lohini\database\doctrine\orm\entities\nestednode' => '/Database/Doctrine/ORM/Entities/NestedNode.php',
		'lohini\database\doctrine\orm\entitymanagerhelper' => '/Database/Doctrine/ORM/EntityManagerHelper.php',
		'lohini\database\doctrine\orm\entityrepository' => '/Database/Doctrine/ORM/EntityRepository.php',
		'lohini\database\doctrine\orm\mapping\classmetadata' => '/Database/Doctrine/ORM/Mapping/ClassMetadata.php',
		'lohini\database\doctrine\orm\mapping\classmetadatafactory' => '/Database/Doctrine/ORM/Mapping/ClassMetadataFactory.php',
		'lohini\database\doctrine\orm\mapping\discriminatormapdiscoverylistener' => '/Database/Doctrine/ORM/Mapping/DiscriminatorMapDiscoveryListener.php',
		'lohini\database\doctrine\orm\mapping\driver\annotationdriver' => '/Database/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php',
		'lohini\database\doctrine\orm\mapping\entitydefaultslistener' => '/Database/Doctrine/ORM/Mapping/EntityDefaultsListener.php',
		'lohini\database\doctrine\orm\mapping\tableprefix' => '/Database/Doctrine/ORM/Mapping/TablePrefix.php',
		'lohini\database\doctrine\orm\querybuilder' => '/Database/Doctrine/ORM/QueryBuilder.php',
		'lohini\database\doctrine\orm\repositories\nestedtreerepository' => '/Database/Doctrine/ORM/Repositories/NestedTreeRepository.php',
		'lohini\database\doctrine\orm\type' => '/Database/Doctrine/ORM/Type.php',
		'lohini\database\doctrine\orm\types\callback' => '/Database/Doctrine/ORM/Types/Callback.php',
		'lohini\database\doctrine\orm\types\password' => '/Database/Doctrine/ORM/Types/Password.php',
		'lohini\database\doctrine\queryexception' => '/Database/Doctrine/ORM/QueryException.php',
		'lohini\database\doctrine\workspace' => '/Database/Doctrine/Workspace.php',
		'lohini\database\models\entities\authconnection' => '/Database/Models/Entities/AuthConnection.php',
		'lohini\database\models\entities\identity' => '/Database/Models/Entities/Identity.php',
		'lohini\database\models\entities\plugin' => '/Database/Models/Entities/Plugin.php',
		'lohini\database\models\entities\upload' => '/Database/Models/Entities/Upload.php',
		'lohini\database\models\entities\user' => '/Database/Models/Entities/User.php',
		'lohini\database\models\entities\userrole' => '/Database/Models/Entities/UserRole.php',
		'lohini\database\models\ientity' => '/Database/Models/IEntity.php',
		'lohini\database\models\iservice' => '/Database/Models/IService.php',
		'lohini\database\models\querybuilder' => '/Database/Models/QueryBuilder.php',
		'lohini\database\models\repositories\base' => '/Database/Models/Repositories/Base.php',
		'lohini\database\models\repositories\plugin' => '/Database/Models/Repositories/Plugin.php',
		'lohini\database\models\repositories\upload' => '/Database/Models/Repositories/Upload.php',
		'lohini\database\models\repositories\user' => '/Database/Models/Repositories/User.php',
		'lohini\database\models\repositories\userrole' => '/Database/Models/Repositories/UserRole.php',
		'lohini\database\models\services\base' => '/Database/Models/Services/Base.php',
		'lohini\database\models\services\identities' => '/Database/Models/Services/Identities.php',
		'lohini\database\models\services\plugins' => '/Database/Models/Services/Plugins.php',
		'lohini\database\models\services\uploads' => '/Database/Models/Services/Uploads.php',
		'lohini\database\models\services\users' => '/Database/Models/Services/Users.php',
		'lohini\di\configurator' => '/DI/Configurator.php',
		'lohini\di\container' => '/DI/Container.php',
		'lohini\di\containerhelper' => '/DI/ContainerHelper.php',
		'lohini\di\texycontainer' => '/DI/TexyContainer.php',
		'lohini\diagnostics\panels\callback' => '/Diagnostics/Panels/Callback.php',
		'lohini\forms\controls\cbox3s' => '/Forms/Controls/CBox3S.php',
		'lohini\forms\controls\datepicker' => '/Forms/Controls/DatePicker.php',
		'lohini\forms\controls\pswdinput' => '/Forms/Controls/PswdInput.php',
		'lohini\forms\controls\resetbutton' => '/Forms/Controls/ResetButton.php',
		'lohini\forms\controls\texyla' => '/Forms/Controls/Texyla.php',
		'lohini\forms\rendering\formrenderer' => '/Forms/Rendering/FormRenderer.php',
		'lohini\loaders\lohiniloader' => '/Loaders/LohiniLoader.php',
		'lohini\loaders\splclassloader' => '/Loaders/SplClassLoader.php',
		'lohini\localization\dictionary' => '/Localization/Dictionary.php',
		'lohini\localization\extractor' => '/Localization/Extractor.php',
		'lohini\localization\filters\latte' => '/Localization/Filters/Latte.php',
		'lohini\localization\filters\lattemacros' => '/Localization/Filters/LatteMacros.php',
		'lohini\localization\filters\nella' => '/Localization/Filters/Nella.php',
		'lohini\localization\ifilter' => '/Localization/IFilter.php',
		'lohini\localization\istorage' => '/Localization/IStorage.php',
		'lohini\localization\itranslator' => '/Localization/ITranslator.php',
		'lohini\localization\languageentity' => '/Localization/LanguageEntity.php',
		'lohini\localization\languages' => '/Localization/Languages.php',
		'lohini\localization\panel' => '/Localization/Panel.php',
		'lohini\localization\pluralforms' => '/Localization/PluralForms.php',
		'lohini\localization\storages\gettext' => '/Localization/Storages/Gettext.php',
		'lohini\localization\translator' => '/Localization/Translator.php',
		'lohini\plugins\basepresenter' => '/Plugins/BasePresenter.php',
		'lohini\plugins\imanager' => '/Plugins/IManager.php',
		'lohini\plugins\manager' => '/Plugins/Manager.php',
		'lohini\plugins\plugin' => '/Plugins/Plugin.php',
		'lohini\plugins\pluginexception' => '/Plugins/PluginException.php',
		'lohini\plugins\securedpresenter' => '/Plugins/SecuredPresenter.php',
		'lohini\presenters\basepresenter' => '/Presenters/BasePresenter.php',
		'lohini\presenters\errorpresenter' => '/Presenters/ErrorPresenter.php',
		'lohini\presenters\texylapresenter' => '/Presenters/TexylaPresenter.php',
		'lohini\presenters\webloaderpresenter' => '/Presenters/WebLoaderPresenter.php',
		'lohini\security\authenticator' => '/Security/Authenticator.php',
		'lohini\security\authenticators\db' => '/Security/Authenticators/DB.php',
		'lohini\security\authenticators\ldap' => '/Security/Authenticators/LDAP.php',
		'lohini\security\authenticators\local' => '/Security/Authenticators/Local.php',
		'lohini\security\user' => '/Security/User.php',
		'lohini\templating\helpers' => '/Templating/Helpers.php',
		'lohini\templating\itemplatefactory' => '/Templating/ITemplateFactory.php',
		'lohini\templating\templatefactory' => '/Templating/TemplateFactory.php',
		'lohini\types\password\password' => '/Types/Password.php',
		'lohini\utils\browscap' => '/Utils/Browscap.php',
		'lohini\utils\browscapexception' => '/Utils/BrowscapException.php',
		'lohini\utils\browser' => '/Utils/Browser.php',
		'lohini\utils\freezableobject' => '/Utils/FreezableObject.php',
		'lohini\utils\network' => '/Utils/Network.php',
		'lohini\utils\tools' => '/Utils/Tools.php',
		'lohini\webloader\cssloader' => '/WebLoader/CssLoader.php',
		'lohini\webloader\filters\ccssfilter' => '/WebLoader/Filters/CCssFilter.php',
		'lohini\webloader\filters\cssurlsfilter' => '/WebLoader/Filters/CssUrlsFilter.php',
		'lohini\webloader\filters\lessfilter' => '/WebLoader/Filters/LessFilter.php',
		'lohini\webloader\filters\prefilefilter' => '/WebLoader/Filters/PreFileFilter.php',
		'lohini\webloader\filters\sass\exception' => '/WebLoader/Filters/Sass/Exception.php',
		'lohini\webloader\filters\sass\extensions\compass\colourstop' => '/WebLoader/Filters/Sass/Extensions/Compass/ColourStop.php',
		'lohini\webloader\filters\sass\extensions\compass\compasslist' => '/WebLoader/Filters/Sass/Extensions/Compass/CompassList.php',
		'lohini\webloader\filters\sass\extensions\compass\config' => '/WebLoader/Filters/Sass/Extensions/Compass/Config.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\colourstops' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/ColourStops.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\constants' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/Constants.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\fontfiles' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/FontFiles.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\imagesize' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/ImageSize.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\inlinedata' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/InlineData.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\lists' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/Lists.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\selectors' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/Selectors.php',
		'lohini\webloader\filters\sass\extensions\compass\functions\urls' => '/WebLoader/Filters/Sass/Extensions/Compass/Functions/Urls.php',
		'lohini\webloader\filters\sass\file' => '/WebLoader/Filters/Sass/File.php',
		'lohini\webloader\filters\sass\parser' => '/WebLoader/Filters/Sass/Parser.php',
		'lohini\webloader\filters\sass\renderers\compact' => '/WebLoader/Filters/Sass/Renderers/Compact.php',
		'lohini\webloader\filters\sass\renderers\compressed' => '/WebLoader/Filters/Sass/Renderers/Compressed.php',
		'lohini\webloader\filters\sass\renderers\expanded' => '/WebLoader/Filters/Sass/Renderers/Expanded.php',
		'lohini\webloader\filters\sass\renderers\nested' => '/WebLoader/Filters/Sass/Renderers/Nested.php',
		'lohini\webloader\filters\sass\renderers\renderer' => '/WebLoader/Filters/Sass/Renderers/Renderer.php',
		'lohini\webloader\filters\sass\script\functionexception' => '/WebLoader/Filters/Sass/Script/ParserExceptions.php',
		'lohini\webloader\filters\sass\script\functions' => '/WebLoader/Filters/Sass/Script/Functions.php',
		'lohini\webloader\filters\sass\script\lexer' => '/WebLoader/Filters/Sass/Script/Lexer.php',
		'lohini\webloader\filters\sass\script\lexerexception' => '/WebLoader/Filters/Sass/Script/ParserExceptions.php',
		'lohini\webloader\filters\sass\script\literals\boolean' => '/WebLoader/Filters/Sass/Script/Literals/Boolean.php',
		'lohini\webloader\filters\sass\script\literals\booleanexception' => '/WebLoader/Filters/Sass/Script/Literals/LiteralExceptions.php',
		'lohini\webloader\filters\sass\script\literals\colour' => '/WebLoader/Filters/Sass/Script/Literals/Colour.php',
		'lohini\webloader\filters\sass\script\literals\colourexception' => '/WebLoader/Filters/Sass/Script/Literals/LiteralExceptions.php',
		'lohini\webloader\filters\sass\script\literals\literal' => '/WebLoader/Filters/Sass/Script/Literals/Literal.php',
		'lohini\webloader\filters\sass\script\literals\literalexception' => '/WebLoader/Filters/Sass/Script/Literals/LiteralExceptions.php',
		'lohini\webloader\filters\sass\script\literals\number' => '/WebLoader/Filters/Sass/Script/Literals/Number.php',
		'lohini\webloader\filters\sass\script\literals\numberexception' => '/WebLoader/Filters/Sass/Script/Literals/LiteralExceptions.php',
		'lohini\webloader\filters\sass\script\literals\string' => '/WebLoader/Filters/Sass/Script/Literals/String.php',
		'lohini\webloader\filters\sass\script\literals\stringexception' => '/WebLoader/Filters/Sass/Script/Literals/LiteralExceptions.php',
		'lohini\webloader\filters\sass\script\operation' => '/WebLoader/Filters/Sass/Script/Operation.php',
		'lohini\webloader\filters\sass\script\operationexception' => '/WebLoader/Filters/Sass/Script/ParserExceptions.php',
		'lohini\webloader\filters\sass\script\parser' => '/WebLoader/Filters/Sass/Script/Parser.php',
		'lohini\webloader\filters\sass\script\parserexception' => '/WebLoader/Filters/Sass/Script/ParserExceptions.php',
		'lohini\webloader\filters\sass\script\scriptfunction' => '/WebLoader/Filters/Sass/Script/ScriptFunction.php',
		'lohini\webloader\filters\sass\script\variable' => '/WebLoader/Filters/Sass/Script/Variable.php',
		'lohini\webloader\filters\sass\tree\commentnode' => '/WebLoader/Filters/Sass/Tree/CommentNode.php',
		'lohini\webloader\filters\sass\tree\commentnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\context' => '/WebLoader/Filters/Sass/Tree/Context.php',
		'lohini\webloader\filters\sass\tree\contextexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\debugnode' => '/WebLoader/Filters/Sass/Tree/DebugNode.php',
		'lohini\webloader\filters\sass\tree\debugnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\directivenode' => '/WebLoader/Filters/Sass/Tree/DirectiveNode.php',
		'lohini\webloader\filters\sass\tree\directivenodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\eachnode' => '/WebLoader/Filters/Sass/Tree/EachNode.php',
		'lohini\webloader\filters\sass\tree\eachnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\elsenode' => '/WebLoader/Filters/Sass/Tree/ElseNode.php',
		'lohini\webloader\filters\sass\tree\extendnode' => '/WebLoader/Filters/Sass/Tree/ExtendNode.php',
		'lohini\webloader\filters\sass\tree\extendnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\fornode' => '/WebLoader/Filters/Sass/Tree/ForNode.php',
		'lohini\webloader\filters\sass\tree\fornodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\functionnode' => '/WebLoader/Filters/Sass/Tree/FunctionNode.php',
		'lohini\webloader\filters\sass\tree\functionnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\ifnode' => '/WebLoader/Filters/Sass/Tree/IfNode.php',
		'lohini\webloader\filters\sass\tree\ifnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\importnode' => '/WebLoader/Filters/Sass/Tree/ImportNode.php',
		'lohini\webloader\filters\sass\tree\importnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\mixindefinitionnode' => '/WebLoader/Filters/Sass/Tree/MixinDefinitionNode.php',
		'lohini\webloader\filters\sass\tree\mixindefinitionnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\mixinnode' => '/WebLoader/Filters/Sass/Tree/MixinNode.php',
		'lohini\webloader\filters\sass\tree\mixinnodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\node' => '/WebLoader/Filters/Sass/Tree/Node.php',
		'lohini\webloader\filters\sass\tree\nodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\propertynode' => '/WebLoader/Filters/Sass/Tree/PropertyNode.php',
		'lohini\webloader\filters\sass\tree\propertynodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\returnnode' => '/WebLoader/Filters/Sass/Tree/ReturnNode.php',
		'lohini\webloader\filters\sass\tree\rootnode' => '/WebLoader/Filters/Sass/Tree/RootNode.php',
		'lohini\webloader\filters\sass\tree\rulenode' => '/WebLoader/Filters/Sass/Tree/RuleNode.php',
		'lohini\webloader\filters\sass\tree\rulenodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\variablenode' => '/WebLoader/Filters/Sass/Tree/VariableNode.php',
		'lohini\webloader\filters\sass\tree\variablenodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sass\tree\whilenode' => '/WebLoader/Filters/Sass/Tree/WhileNode.php',
		'lohini\webloader\filters\sass\tree\whilenodeexception' => '/WebLoader/Filters/Sass/Tree/NodeExceptions.php',
		'lohini\webloader\filters\sassfilter' => '/WebLoader/Filters/SassFilter.php',
		'lohini\webloader\filters\xcssfilter' => '/WebLoader/Filters/XCssFilter.php',
		'lohini\webloader\jsloader' => '/WebLoader/JsLoader.php',
		'lohini\webloader\texylaloader' => '/WebLoader/TexylaLoader.php',
		'lohini\webloader\webloader' => '/WebLoader/WebLoader.php',
		'lohini\webloader\webloadercachestorage' => '/WebLoader/WebLoaderCacheStorage.php',
		);


	/**
	 * Returns singleton instance with lazy instantiation
	 * @return LohiniLoader
	 */
	public static function getInstance()
	{
		if (self::$instance===NULL) {
			self::$instance=new static;
			}
		return self::$instance;
	}

	/**
	 * Handles autoloading of classes or interfaces
	 * @param string $type
	 * @see AutoLoader::tryLoad()
	 */
	public function tryLoad($type)
	{
		$type=ltrim(strtolower($type), '\\');
		if (isset($this->list[$type])) {
			\Nette\Utils\LimitedScope::load(LOHINI_DIR.$this->list[$type]);
			self::$count++;
			}
	}
}
